# fly.toml app configuration file generated for dominoes-api on 2023-07-14T23:25:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dominoes-api"
primary_region = "mia"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  DB_CONNECTION = "mysql"
  DB_HOST = "sql9.freesqldatabase.com"
  DB_PORT= "3306"
  DB_DATABASE= "sql9632837"
  DB_USERNAME = "sql9632837"
  DB_PASSWORD = "BDxUpmlzrr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

